const arr = [
  "Loading...",
  "Faire l'impossible",
  "Vérification des offres",
  "Création d'entités générées aléatoirement",
  "Frapper votre clavier ne rendra pas cela plus rapide",
  "Génération de plans pour des déplacements plus rapides que la lumière",
  "DING!",
  "Faire quelque chose que vous ne voulez pas savoir",
  "Est-ce que quelqu'un lit réellement ceci?",
  "Vérification du rayon anti-camp",
  "Ne paniquez pas",
  "Dépoussiérer les grimoires",
  "S'assurer que tout fonctionne à la perfection",
  "S'assurer que les gnomes sont encore courts",
  "Remplir des halfelins avec une tarte",
  "Grrr. Écorce. Écorce. Grrr.",
  "Avez-vous étreint un Iksar aujourd'hui?",
  "Avez-vous essayé des céréales Batwing Crunchies?",
  "Vérifications des cvs",
  "Cacher l'herbe à chat de Vah Shir",
  "Honk si vous mangez des gnomes",
  "Si vous pressez les elfes noirs, vous ne recevez pas de vin",
  "Dans le gris, personne ne peut vous entendre crier",
  "N'est-il pas temps de laver votre armure?",
  "Karnor ... Plus de 41 milliards de trains desservis",
  "Chargement, n'attendez pas si vous ne le souhaitez pas",
  "Regarde derrière toi",
  "À la recherche de graphiques",
  "Regardant vers le haut les kilts barbares",
  "Maintenant en train de se reproduire Fippy_Darkpaw_432,366,578",
  " Huilage de montres",
  "Donner des ailes aux porcs",
  "Pizza ... L'autre Autre Viande Blanche",
  "Polissage de front érudit",
  " Se préparer à vous faire tourner rapidement",
  "Munition rafraîchissante Death Touch",
  "Ruiner mes propres terres",
  "Ponçage des elfes des bois ... maintenant 34% plus lisse.",
  " Aiguiser les griffes",
  "Aiguiser les épées",
  "Faire apparaître vos caractères01",
  "Robes de Haut Elfe",
  "Corder des arcs",
  "Ogres stupéfiants",
  "Enseigner aux serpents",
  "Je vous avais dit qu'il n'était pas fait de fromage",
  "Avertissement: les demi-elfes sont maintenant .49999 elfes.",
  "Trolls frappant avec bâton laid",
  "Pourquoi les clercs brûlent-ils toujours le pain?",
  "Je me demande si les pneus Phinegal Autropos de fruits de mer?",
  "Vous êtes devenu meilleur à pétiller! (47)",
  " Vous êtes devenu meilleur en chargement! (15)"
];
export default arr;
